name: template
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  gap:
  google_fonts: ^6.2.1
  go_router:
  adaptive_theme:
  bounce: ^1.0.2
  motion: ^2.0.1
  universal_io: ^2.2.2
  table_calendar: ^3.0.9
  intl: ^0.18.1
  uuid: ^4.1.0
  url_launcher: ^6.2.5
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true